### ISSUE TITLE
Support for Alias Configuration file

### ISSUE THREAD

**Issue by hashd** [davrodpin/mole#104]
Would be nice if aliases can be loaded off a configuration like `~/.mole/aliases.config` or something.

- It'll be easier to share config across colleagues
- It'll be easier to bulk edit aliases at the same time if there are any changes that apply to all or most of them

Definitely can live with the current way of doing things, thought this could be more convenient. If such a thing already exists, do point me towards that

**Comment by davrodpin** [comment]
Good news for you, @hashd, all aliases are stored on `$HOME/.mole.conf`

**Comment by hashd** [comment]
perfect, you can close this issue

would be nice to document that in the README so that people are aware of the fact and can take advantage accordingly

**Comment by hashd** [comment]
nevertheless, this project makes my life so much simpler, thanks for building and maintaining it
