### ISSUE TITLE
Mole fails in Ubuntu on Windows / WSL

### ISSUE THREAD

**Issue by oal** [davrodpin/mole#108]
## Affected Version
0.5.0, also tested 0.4

## Expected Behavior
Tunnel should be set up.

## Current Behavior
When launching `mole`, it crashes and outputs:
```ERRO[0000] error generating ssh client config: extra data in encoded key  tunnel="[channels:[[local=127.0.0.1:8080, remote=127.0.0.1:8080]], server:IP:22]"```

## Steps to Reproduce
1. Open a WSL (Windows Subsystem for Linux) terminal
2. Run:
```
mole -v -local :8080 -remote :8080 -server someserver
```

Output:
```
DEBU[0000] cli options                                   options="[local=:8080, remote=:8080, server=someserver, key=, verbose=true, help=false, version=false, detach=false, insecure=false, keep-alive-interval=10s, timeout=3s, connection-retries=3, retry-wait=3s]"
DEBU[0000] using ssh config file from: /home/username/.ssh/config
DEBU[0000] server: [name=someserver, address=123.123.123.123:22, user=username]
DEBU[0000] tunnel: [channels:[[local=127.0.0.1:8080, remote=127.0.0.1:8080]], server:123.123.123.123:22]
ERRO[0000] error generating ssh client config: extra data in encoded key  tunnel="[channels:[[local=127.0.0.1:8080, remote=127.0.0.1:8080]], server:123.123.123.123:22]"
```

**Comment by davrodpin** [comment]
Hi @oal,

I just tested on windows10 + wsl2 using ubuntu and mole seem to be working fine.
The error message that you paste above, `extra data in coded key`, is indicating that the key used to connect to the ssh server is invalid.

https://github.com/davrodpin/mole/blob/61590247f8a5222fa6fe10d526ebe8725c98cb38/tunnel/key.go#L127

```
import "encoding/pem"

func Decode(data []byte) (p *Block, rest []byte)

Decode will find the next PEM formatted block (certificate, private key etc) in
the input. It returns that block and the remainder of the input. If no PEM data
is found, p is nil and the whole of the input is returned in rest.
```

Are you able to ssh to the ssh server using that key without using mole?

**Comment by oal** [comment]
Hi!

Thanks for testing. Normal SSH sessions are working. `ssh myserver` lets me in immediately.

I think I may be on WSL1 (Windows 10 ver 10.0.18362.418).

**Comment by oal** [comment]
I tried generating a new ssh key, and it mole works now. I've used this old key for a long time, and it's always worked for normal ssh sessions. Not sure what's wrong with it, but not an issue with mole then. (y)

**Comment by davrodpin** [comment]
> I tried generating a new ssh key, and mole works now. I've used this old key for a long time, and it's always worked for normal ssh sessions. Not sure what's wrong with it, but not an issue with mole then.

Hi @oal, any information you could share about how this key was generated? I would like to take this opportunity to improve mole.

**Comment by oal** [comment]
Sure! I think it was generated in MacOS in 2014, and I've carried it with me since then. No passphrase.
