### ISSUE TITLE
New feature: Make timeout connection to ssh server configurable

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#12]
New CLI flag to configure the client timeout while trying to establish a connection with the ssh server.

**Potential Solution**

Along with the addition of a new cli flag, the following code would need to be changed to use the given timeout value:

https://github.com/davrodpin/mole/blob/8f08748587247571cd489d6b25e579d16758cf8b/tunnel/tunnel.go#L239

**Comment by m3hari** [comment]
I will take this

**Comment by KFPJ4XL9JMNP** [comment]
Thank you

**Comment by BenMcH** [comment]
@m3hari Are you still planning to complete this? If so, feel free to look at [my PR](https://github.com/davrodpin/mole/pull/14) for implementation ideas. It could serve as a template for adding this feature since it's doing very similar work.

**Comment by m3hari** [comment]
@BenMcH Thank you I will look into it. Hopefully, I will make my PR soon.
