### ISSUE TITLE
New feature: use LocalForward option from SSH config file

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#13]
SSH config file supports an option, `LocalForward` that specifies a local port to be forwarded to a remote machine over the ssh connection established to the given server.

Making `mole` to use that option would help users that are already using it on their ssh config file to:

  * Not duplicate the option in the ssh config file (i.e. `LocalForward`),  and in the `mole` aliases file (i.e. `local` and `remote`)
  * Make `mole` easier to use since there `-local` and `-remote` options would be required

From https://www.ssh.com/ssh/config/:

> LocalForward
>
> Specifies that a TCP port on the local machine be forwarded over the secure channel to the specified
> host and port from the remote machine. The first argument must be [bind_address:]port and the
> second argument must be host:port.

**Comment by 4ltieres** [comment]
I'm working on this.

**Comment by davrodpin** [comment]
PR #18
