### ISSUE TITLE
Support all types of SSH tunnels

### ISSUE THREAD

**Issue by dschep** [davrodpin/mole#22]
Interesting tool @davrodpin!

I'd expect a tool for managing SSH tunnels to support reverse (`ssh -R`) and dynamic (`ssh -D`) tunnels.

Reverse tunnels could be implemented by a `-reverse` flag that causes ssh to be spawned with `-R` instead of `-L`.

Dynamic tunnels could be implemented by a `-dynamic` flag with makes mole not need(in fact should error if it is present) the `-remote` flag.

**Comment by davrodpin** [comment]
Thanks, @dschep! Also thanks for providing feedback. 

We definitively want to support more types of tunnels. 

I've got similar feedback from Hacker News. I am going to paste here to hep on the discussion.

```
vectorEQ:

there's multiple ways to make tunnels in ssh. -L is one of them (local forwarding). basically, local, remote and dynamic forwarding are possible. there's some interesting uses for the latter 2 as well so if you only know -L it might be nice to check out the other methods and how you can use those. You can for example, forward a remote localhost port of a server to your own localhost, and then have a fully encrypted channel to some internal or locally bound service. for example if some server hosts a site on it's loopback or some service is listening there which you want to interact with, then you can do it directly from your own machine instead of through an active ssh session. (for example with websites this is useful, because then you can have a graphical browser instead of links via ssh x11 forwarding or w/e)
```

**Comment by davrodpin** [comment]
Closing this one. Remote Port Forwarding was implemented o b4239d and I've created a new issue for Dynamic Port Forwarding, #118
