### ISSUE TITLE
Reconnect to ssh server if connection drops

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#24]
The feedback below came from a Hacker News discussion:

> tjoff
>  I don't know if it does but I kind of assumed/hoped it did reconnect if a connection drops. But I can't find anything about it so I guess it doesn't.reply | I don't know if it does but I kind of assumed/hoped it did reconnect if a connection drops. But I can't find anything about it so I guess it doesn't.reply
>> earthscienceman 5 hours ago 
>> Uh. I run an autossh program on the host in question. It auto-runs ssh connections when they drop, including tunnels. https://www.everythingcli.org/ssh-tunnelling-for-fun-and-profit-autossh/

This might be a good feature to implement, maybe a new optional flag to indicate how many consecutive attempts should be made before giving up.

**Comment by jessebarton** [comment]
I'm pretty new to open source but i'm willing to give this one a shot. Since its Hacktober! Any pointers on getting started with adding a feature like this I've worked with Go's crypto/ssh library a bit.

Looks like adding a Optional Flag to indicate consecutive attempts is a criteria for this before it times out completely. Is there any other criteria you can think of? Thanks!

**Comment by davrodpin** [comment]
> I'm pretty new to open source but i'm willing to give this one a shot. Since its Hacktober! Any pointers on getting started with adding a feature like this I've worked with Go's crypto/ssh library a bit.
> 
> Looks like adding a Optional Flag to indicate consecutive attempts is a criteria for this before it times out completely. Is there any other criteria you can think of? Thanks!

Thank you very much for considering contributing to the project, @jessebarton. And don't worry about being new to open source, this is my first project 😝 

The more I think about this feature, the more I see a need for two different requirements:

1. **Server Reconnect**: the app should try to reconnect to the ssh server whenever the connection gets dropped. 
2. **Keep Alive**: the app should keep sending synthetic packets to the ssh server to not allow the connection to time out.

Let's focus this issue on 1 and I will cover 2 on another one.

Every time the connection to the ssh gets dropped by any reason, the app should try to reconnect after some period of time. 

By default, the reconnect interval should be `10 seconds` and user could use the `-reconnect-after` flag to override this value.

Take a look on [Tunnel#Start()](https://github.com/davrodpin/mole/blob/7e939909614faec42c96d4aa0d96e33fa25d71b6/tunnel/tunnel.go#L126). 
There is a select at the end of the method that is waiting for an error. Any problem while connecting to either the ssh server or the remote service is handled there. That might be the place to handle the retry logic, instead of letting the app to end.

**Comment by jessebarton** [comment]
@davrodpin I will go ahead and take a look at this and see how far along i can get. Thanks for the detailed explanation of what you would like to see happen with this change. Appreciate it very much! I'll keep you posted if i have questions and on progress that i make.

**Comment by ei8fdb** [comment]
(Probably a silly question, so....)

This behaviour (auto reconnect if connection to SSH server drops) is something that should be default? Thinking about all my SSH tunnels if any drop, I want them to reconnect. 

Hence - there probably isn't a need for this to be configurable in a UI? The most I'd expect is a configurable:
 
- [ ] auto reconnect if connection drops 

option?

**Comment by davrodpin** [comment]
Hi @ei8fdb, 

> This behaviour (auto reconnect if connection to SSH server drops) is something that should be default?

Yes, both `Server Reconnect` and `Keep Alive` should be enabled by default. 
We want  optional arguments for the amount of time `mole` will wait before trying to connect again and how many attempts `mole` should make once the server disconnects before giving up.
