### ISSUE TITLE
Provide short version of flag names

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#25]
For users familiar with the app, having a shorter version of the flag names could save some time while typing the option.

**Proposal for mole's flag names supported on version 0.5.0**

| long | short |
|-----|------|
| -alias | -a |
| -aliases | -I |
| -connection-retries | -R |
| -delete | -d |
| -detach | -x |
| -help | -h |
| -insecure | -i |
| -keep-alive-interval | -K |
| -key | -k |
| -local | -l |
| -remote | -r |
| -retry-wait | -w |
| -server | -s |
| -start | -S |
| -stop | -o |
| -timeout | -t |
| -verbose | -v |
| -version | <none> |

**Comment by jcox250** [comment]
Do you want to try and do this still using the stdlib flag package? Or would you be happy for a library like cobra to be used?

**Comment by davrodpin** [comment]
Thanks for considering contributing to the project, @jcox250!

[Cobra](https://github.com/spf13/cobra) seems to be slick, I like that!

Moving to it will probably break the backwards compatibility, but will provide a robust and elegant way of handling the flags. We just need to make sure it's going to be very easy for the users to understand the commands and flags.

Please feel free to make the modifications and let me know where I can help.

**Comment by jcox250** [comment]
Sweet! I'll have a stab at it over the weekend

**Comment by jcox250** [comment]
@davrodpin So I've had a go at this and think I've got something that should work. I've used [spf13/pflag](https://github.com/spf13/pflag) instead of cobra because it's API meant the code could pretty much stay the same and just use `pflag` in any place where the stdlib `flag` package was used.

One issue I've run into is short version of flag names aren't allowed to be longer than 1 character which rules out using `st` for start and also means that one of `--version` or `--verbose` can't use `-v` as a short flag. 

Do you've any thoughts on what you would want the short version for these flags to be instead?

Also, just want to double check that when I put the PR up do you want me to check the `spf13/pflag` into the vendor directory?

**Comment by jcox250** [comment]
If it helps I opened a PR on my fork so you can have a look when deciding short names. Still need to add tests for the short names but I can do that after we get the short names sorted.
https://github.com/jcox250/mole/pull/1

**Comment by davrodpin** [comment]
@jcox250, I saw value on using cobra because we would make all supported use cases to follow the `<command> <args>` patterns promoted by the library. 
`pflag` seems to do almost the same thing as `flag`, with the addition of a few helpers, so why not stick the the standard `flag` package, so no dependencies are added to the project?

**Comment by condemil** [comment]
You can also check out go-flags, I am using it in my projects https://github.com/jessevdk/go-flags

**Comment by jcox250** [comment]
@davrodpin So the one advantage that you get from `pflag` that you don't get from `flag` is the ability to have short flag names which you can't get with `flag`. I could change it to use cobra instead though if you want? I just settled of `pflag` because I thought it would require less maintenance/changes to the code base.

**Comment by davrodpin** [comment]
@jcox250, please proceed with the implementation with `pflag`. We can think on redesigning the flags and how the user interacts with the tool later.

**Comment by ricardoseriani** [comment]
Since the PR of this is not already merged, can I try do add this and open a new PR ?

I'm thinking about using the `github.com/spf13/pflag` package.
If so, what will be the sort flag of the `-start` ? Because, as noted,  short version of flag names aren't allowed to be longer than 1 character.

**Comment by davrodpin** [comment]
> Since the PR of this is not already merged, can I try do add this and open a new PR ?

That would be great, @ricardoseriani, thank you! Please take a look on #36 to understand previous design decisions.

> I'm thinking about using the `github.com/spf13/pflag` package.

I see no problem with that. 
Just as a mental note, I want to move the entire application to use something like [cobra](https://github.com/spf13/cobra) at some time in the future to have a better modularization of each workflow inside mole.

> If so, what will be the sort flag of the `-start` ? Because, as noted, short version of flag names aren't allowed to be longer than 1 character.

I've updated the issue description with a new proposal for the short name for the flags

**Comment by ricardoseriani** [comment]
For the usage, should I show both versions of flags ?

I'm thing about show the first lines using both flags (using | as separator) and the other lines show only the long flag, like this:

```
usage:
	mole [--verbose|-v] [--insecure|-i] [--detach|-x] (--local|-l [<host>]:<port>)... (--remote|-r [<host>]:<port>)... --server|-s [<user>@]<host>[:<port>] [--key|-k <key_path>] [--keep-alive-interval|-K <time_interval>] [--connection-retries|-R <retries>] [--retry-wait|-w <time>]
	mole --alias <alias_name> [--verbose] (--local [<host>]:<port>)... (--remote [<host>]:<port>)... --server [<user>@]<host>[:<port>] [--key <key_path>] [--keep-alive-interval <time_interval>] [--connection-retries <retries>] [--retry-wait <time>]
	mole --alias <alias_name> --delete
	mole --start <alias_name>
	mole --help
	mole --version
```

Or you think that I should add an example of using the short flags in another line (to avoid confusing new people) ?

**Comment by davrodpin** [comment]
Let's keep the long names in the examples only. One will use the short names probably when they get used to the tool so we can consider it an "advanced" feature.
