### ISSUE TITLE
New feature: Persistent Connection

### ISSUE THREAD

**Issue by davrodpin** [davrodpin/mole#26]
The app could keep sending a keep-alive packet to the ssh server to avoid connection time outs configured on the server side.

Those synthetic, null packets should be sent every `10 seconds` by default, with a flag , `-ka-interval`, to allow the user to override this value.

In case the ssh server does not respond to the keep-alive packets, the app should keep trying to send them `three (3) times` before giving up and closing the connection. The number of attempts could be overridden by the user using the flag `-ka-attempt`.

`$ mole -remote :443 -server example -ka-interval "5 seconds" -ka-attempt 10`

Related-To: #24

**Comment by davrodpin** [comment]
I will work on this one.

**Comment by mukulrawat1986** [comment]
Can I work on this @davrodpin ?

**Comment by davrodpin** [comment]
Hi @mukulrawat1986, you would need to understand how the [crypto/ssh](https://godoc.org/golang.org/x/crypto/ssh) library and [ssh](https://tools.ietf.org/html/rfc4254) works to implement this feature.
If you're not familiar with them, I would say this change will not be so straightforward and maybe you should consider another [issue](https://github.com/davrodpin/mole/issues), but that is totally up to you 😄 

Take your time and let me know if you need any help.

**Comment by mukulrawat1986** [comment]
Thanks for letting me know. Any other issue you can suggest which I may try first? I would love to work with this so I can take my time and start from something small.

**Comment by davrodpin** [comment]
> Thanks for letting me know. Any other issue you can suggest which I may try first? I would love to work with this so I can take my time and start from something small.

Maybe #31.
