### ISSUE TITLE
error generating ssh client config: ssh: cannot decode encrypted private keys

### ISSUE THREAD

**Issue by bigeast** [davrodpin/mole#30]
## Expected Behavior

Requests to localhost:3389 should be forward to remote:8888, 

## Current Behavior

localhost:3389 can't be reached, and 
`ERRO[0002] error generating ssh client config: ssh: cannot decode encrypted private keys  tunnel="[local:127.0.0.1:3389, server:my.Server.I.P:myServerPort, remote:127.0.0.1:8888]"`

## Steps to Reproduce

1. In remote server, run `jupyter lab`, this will run the jupyter on port 8888.
2. Add the server information into **~/.ssh/config**:
```
Host myServer
  Hostname my.Server.I.P
  Port myServerPort
  User user
  IdentityFile ~/.ssh/id_rsa
```
3. Run `mole -v -local :3389 -remote :8888 -server myServer`.
4. Visit `http://localhost:3389/` in a browser.

The ssh-agent is running and I added the ssh key into the macOS keychain by `ssh-add -K ~/.ssh/id_rsa`. After the error, I remove it from the keychain by `ssh-add -d ~/.ssh/id_rsa`, but no luck. I also killed the ssh-agent process, still the same error.

Before mole, I use this ssh command: `ssh -N -p myServerPort devops@my.Server.I.P -L localhost:3389:localhost:8888` and it works fine.

**Comment by davrodpin** [comment]
@bigeast, thank you for filing the issue!

Unfortunately, `mole` does not have support for encrypted private keys yet.

We would need to improve the tool to detect if the key is encrypted and prompt the user for the password (not flag for that matter, please). Some references:

* https://godoc.org/golang.org/x/crypto/ssh#ParseDSAPrivateKey
* https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKey
* https://godoc.org/golang.org/x/crypto/ssh#ParseRawPrivateKeyWithPassphrase

**Comment by akshaychhajed** [comment]
@bigeast Maybe I can add this feature
