### ISSUE TITLE
under osx not using ssh-agent

### ISSUE THREAD

**Issue by saltmaster-at** [davrodpin/mole#87]
## Affected Version
mole 0.4.0 installed through brew 
MacOS Mojave 10.14.6 (18G95)

## Expected Behavior
mole should use the existing key-agent socket SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.xXxxxX/Listeners

## Current Behavior
asks for key-password

## Steps to Reproduce

1. configure a tunnel
2. start ssh-agent and make sure to set ENV
3. start mole
4. -> key-password is asked

**Comment by davrodpin** [comment]
Could you provide the mole's output with the `-v` flag set?

**Comment by saltmaster-at** [comment]
ssh-add -l
4096 SHA256:xxxxx /Users/martinmenhart/.ssh/id_rsa (RSA)
3072 SHA256:xxxxx /Users/martinmenhart/.ssh/id_dsa (DSA)

martinmenhart at MartinMsMBP-2 in ~
$ cat ~/.mole.conf
[tunnels]
  [tunnels.rbproxy01]
    local = [":8991"]
    remote = [":8998"]
    server = "redhybcprxp01"
    key = ""
    verbose = true
    help = false
    version = false
    detach = false

martinmenhart at MartinMsMBP-2 in ~
$ mole -start rbproxy01 -v
DEBU[0000] cli options                                   options="[local=:8991, remote=:8998, server=SOMESERVER, key=, verbose=true, help=false, version=false, detach=false]"
DEBU[0000] using ssh config file from: /Users/martinmenhart/.ssh/config
The key provided is secured by a password. Please provide it below:
Password:

martinmenhart at MartinMsMBP-2 in ~
$ ssh SOMESERVER date
Fri Oct  4 14:22:24 CEST 2019

**Comment by davrodpin** [comment]
Thank, @saltmaster-at . 

Mole does not include support for ssh-agent yet. 

We could leverage the [ssh-agent client](https://godoc.org/golang.org/x/crypto/ssh/agent) from x/crypto/ssh to implement this feature.

**Comment by Spitemare** [comment]
I'd like to take shot at this. I've got some preliminary changes that work, but need some cleanup.

Right now I'm just using whatever socket SSH_AUTH_SOCK points at. I don't really think this needs to be configurable as that is the environment variable set when starting ssh-agent traditionally (`eval $(ssh-agent)`).
