### ISSUE TITLE
panic: non-positive interval for NewTicker

### ISSUE THREAD

**Issue by prologic** [davrodpin/mole#88]
When I run `mole -start <alias>` it panics with:

```
$ mole -start nightly
The key provided is secured by a password. Please provide it below:
Password:
panic: non-positive interval for NewTicker

goroutine 9 [running]:
time.NewTicker(0x0, 0x0)
	/usr/local/Cellar/go/1.13/libexec/src/time/tick.go:23 +0x147
github.com/davrodpin/mole/tunnel.(*Tunnel).keepAlive(0xc0000e0200)
	/Users/james/go/src/github.com/davrodpin/mole/tunnel/tunnel.go:300 +0x44
created by github.com/davrodpin/mole/tunnel.(*Tunnel).dial
	/Users/james/go/src/github.com/davrodpin/mole/tunnel/tunnel.go:290 +0x23f
```

Unclear what version I'm running:

```#!sh
$ mole --version
mole unversioned
```

I originally installed with `go get -u ...`

**Comment by prologic** [comment]
Checking out the code and updating to master and rebuilding/reinstalling from source results int he same error; so I suspect this is a bug currently in master.

**Comment by prologic** [comment]
Logging the value of `app.KeepAliveInterval` shows:

```
INFO[0002] t.KeepAliveInterval: #0s
```

For some reason this is either getting set to `0s` or is the zero value of `time.Duration`

**Comment by prologic** [comment]
I'm sort of at a loss here :/

```#!sh
$ sift KeepAliveInterval
cli/cli.go:34:	KeepAliveInterval time.Duration
cli/cli.go:62:	f.DurationVar(&c.KeepAliveInterval, "keep-alive-interval", 10*time.Second, "(optional) time interval for keep alive packets to be sent")
tunnel/tunnel.go:125:	// KeepAliveInterval is the time period used to send keep alive packets to
tunnel/tunnel.go:127:	KeepAliveInterval time.Duration
tunnel/tunnel.go:300:	ticker := time.NewTicker(t.KeepAliveInterval)
tunnel/tunnel_test.go:352:	tun.KeepAliveInterval = 10 * time.Second
cmd/mole/main.go:276:	log.Infof("t.KeepAliveInterval: #%v", app.KeepAliveInterval)
cmd/mole/main.go:278:	t.KeepAliveInterval = app.KeepAliveInterval
```

Inspecting the code and debugging it a little bit shows that we are missing `t.KeepAliveInterval` from `app.KeepAliveInterface` which _should_ be set from the `f.DurationVar(&c.KeepAliveInterval` on L62 of cli/cli.go

**Comment by davrodpin** [comment]
Hi @prologic,

Thanks for reporting the bug.

Do you mind sharing the alias configuration options associated with your
alias named “nightly” that is stored in “$HOME/.mole.conf”?

**Comment by prologic** [comment]
Sure. Nothing too special here:

```
[tunnels]
  [tunnels.nightly]
    local = ["127.0.0.1:4646"]
    remote = [":4646"]
    server = "nightly"
    key = ""
    verbose = false
    help = false
    version = false
    detach = false
```

It was created with `mole -alias ...` obviously. I've not touched it.

**Comment by davrodpin** [comment]
@prologic,  I am able to reproduce the issue.

mole [0.4.0](https://github.com/davrodpin/mole/tree/v0.4.0) is free from this bug.

**Comment by prologic** [comment]
Oh so I should downgrade in the meantime until master is fixed?

**Comment by davrodpin** [comment]
> Oh so I should downgrade in the meantime until master is fixed?

Yes, please :)
